### PR TITLE
Allow configuration of tls mode for registry proxy.

### LINKED ISSUE #37: Lots of manager messages
When I run the scalabrad manager, I get lots of INFO messages (see below), presumably about trying to connect. Another one comes up every 10 seconds or so. Are these important/useful, or are they just a pest which should be eliminated? Running scalabrad-0.5.0 from bintray.

```
17:57:09.119 [main] INFO  org.labrad.manager.Manager$ - registry location: R:\_L
abRADRegistry_, format=delphi
17:57:09.124 [main] INFO  org.labrad.manager.Manager$ - Using saved certificate
for host 'localhost'. certFile=C:\Users\rottmayer-user\.labrad\manager\certs\loc
alhost.cert, keyFile=C:\Users\rottmayer-user\.labrad\manager\keys\localhost.key
17:57:10.371 [main] INFO  org.labrad.manager.Listener - now accepting labrad con
nections: port=7682, tlsPolicy=STARTTLS
17:57:10.373 [main] INFO  org.labrad.manager.Listener - now accepting labrad con
nections: port=7643, tlsPolicy=ON
17:57:17.271 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49510, local=/128.111.8.222:7682, isLocalConnection=false
17:57:27.301 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49513, local=/128.111.8.222:7682, isLocalConnection=false
17:57:37.333 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49516, local=/128.111.8.222:7682, isLocalConnection=false
17:57:39.847 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/127.0.0.1:51451, local=/127.0.0.1:7682, isLocalConnection=true
17:57:47.342 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49519, local=/128.111.8.222:7682, isLocalConnection=false
17:57:57.359 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49526, local=/128.111.8.222:7682, isLocalConnection=false
17:58:04.657 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/127.0.0.1:51486, local=/127.0.0.1:7682, isLocalConnection=true
17:58:07.370 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49529, local=/128.111.8.222:7682, isLocalConnection=false
17:58:09.814 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/127.0.0.1:51495, local=/127.0.0.1:7682, isLocalConnection=true
17:58:17.378 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49532, local=/128.111.8.222:7682, isLocalConnection=false
17:58:27.432 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49535, local=/128.111.8.222:7682, isLocalConnection=false
17:58:37.488 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49542, local=/128.111.8.222:7682, isLocalConnection=false
17:58:39.599 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/127.0.0.1:51502, local=/127.0.0.1:7682, isLocalConnection=true
17:58:47.496 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49545, local=/128.111.8.222:7682, isLocalConnection=false
17:58:57.537 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49548, local=/128.111.8.222:7682, isLocalConnection=false
17:59:07.548 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49551, local=/128.111.8.222:7682, isLocalConnection=false
17:59:17.556 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49558, local=/128.111.8.222:7682, isLocalConnection=false
17:59:27.563 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49561, local=/128.111.8.222:7682, isLocalConnection=false
17:59:37.598 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49564, local=/128.111.8.222:7682, isLocalConnection=false
17:59:47.604 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49567, local=/128.111.8.222:7682, isLocalConnection=false
17:59:57.612 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49574, local=/128.111.8.222:7682, isLocalConnection=false
18:00:07.192 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.122:62855, local=/128.111.8.222:7682, isLocalConnection=false
18:00:07.622 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49577, local=/128.111.8.222:7682, isLocalConnection=false
18:00:17.623 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49580, local=/128.111.8.222:7682, isLocalConnection=false
18:00:27.636 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49583, local=/128.111.8.222:7682, isLocalConnection=false
18:00:37.644 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49590, local=/128.111.8.222:7682, isLocalConnection=false
18:00:47.649 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49593, local=/128.111.8.222:7682, isLocalConnection=false
18:00:47.659 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.122:62858, local=/128.111.8.222:7682, isLocalConnection=false
18:00:57.664 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49596, local=/128.111.8.222:7682, isLocalConnection=false
18:01:07.673 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49599, local=/128.111.8.222:7682, isLocalConnection=false
18:01:17.681 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49606, local=/128.111.8.222:7682, isLocalConnection=false
18:01:27.686 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49609, local=/128.111.8.222:7682, isLocalConnection=false
18:01:37.691 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49612, local=/128.111.8.222:7682, isLocalConnection=false
18:01:47.702 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49615, local=/128.111.8.222:7682, isLocalConnection=false
18:01:57.706 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49622, local=/128.111.8.222:7682, isLocalConnection=false
18:02:06.030 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/127.0.0.1:51532, local=/127.0.0.1:7682, isLocalConnection=true
18:02:07.720 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49625, local=/128.111.8.222:7682, isLocalConnection=false
18:02:17.729 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49628, local=/128.111.8.222:7682, isLocalConnection=false
18:02:27.738 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49631, local=/128.111.8.222:7682, isLocalConnection=false
18:02:37.744 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49638, local=/128.111.8.222:7682, isLocalConnection=false
18:02:47.753 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49641, local=/128.111.8.222:7682, isLocalConnection=false
18:02:58.045 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49644, local=/128.111.8.222:7682, isLocalConnection=false
18:03:08.057 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49647, local=/128.111.8.222:7682, isLocalConnection=false
18:03:18.064 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49654, local=/128.111.8.222:7682, isLocalConnection=false
18:03:28.075 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49657, local=/128.111.8.222:7682, isLocalConnection=false
18:03:38.081 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49660, local=/128.111.8.222:7682, isLocalConnection=false
18:03:45.875 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.122:62911, local=/128.111.8.222:7682, isLocalConnection=false
18:03:48.089 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49663, local=/128.111.8.222:7682, isLocalConnection=false
18:03:58.098 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49670, local=/128.111.8.222:7682, isLocalConnection=false
18:04:08.114 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49673, local=/128.111.8.222:7682, isLocalConnection=false
18:04:18.115 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49676, local=/128.111.8.222:7682, isLocalConnection=false
18:04:28.126 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49679, local=/128.111.8.222:7682, isLocalConnection=false
18:04:38.137 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49686, local=/128.111.8.222:7682, isLocalConnection=false
18:04:48.148 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49689, local=/128.111.8.222:7682, isLocalConnection=false
18:04:58.225 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49692, local=/128.111.8.222:7682, isLocalConnection=false
18:05:08.228 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49695, local=/128.111.8.222:7682, isLocalConnection=false
18:05:18.234 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49702, local=/128.111.8.222:7682, isLocalConnection=false
18:05:28.245 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49705, local=/128.111.8.222:7682, isLocalConnection=false
18:05:38.258 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49708, local=/128.111.8.222:7682, isLocalConnection=false
18:05:48.262 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49711, local=/128.111.8.222:7682, isLocalConnection=false
18:05:58.276 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49718, local=/128.111.8.222:7682, isLocalConnection=false
18:06:08.276 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49721, local=/128.111.8.222:7682, isLocalConnection=false
18:06:18.290 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49724, local=/128.111.8.222:7682, isLocalConnection=false
18:06:28.296 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49727, local=/128.111.8.222:7682, isLocalConnection=false
18:06:38.304 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49734, local=/128.111.8.222:7682, isLocalConnection=false
18:06:48.319 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49737, local=/128.111.8.222:7682, isLocalConnection=false
18:06:58.319 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49740, local=/128.111.8.222:7682, isLocalConnection=false
18:07:08.329 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49743, local=/128.111.8.222:7682, isLocalConnection=false
18:07:12.241 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.122:62932, local=/128.111.8.222:7682, isLocalConnection=false
18:07:18.339 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49750, local=/128.111.8.222:7682, isLocalConnection=false
18:07:28.349 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49753, local=/128.111.8.222:7682, isLocalConnection=false
18:07:38.350 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49756, local=/128.111.8.222:7682, isLocalConnection=false
18:07:48.361 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49759, local=/128.111.8.222:7682, isLocalConnection=false
18:07:58.371 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49766, local=/128.111.8.222:7682, isLocalConnection=false
18:08:08.371 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49769, local=/128.111.8.222:7682, isLocalConnection=false
18:08:18.402 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49772, local=/128.111.8.222:7682, isLocalConnection=false
18:08:28.433 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49775, local=/128.111.8.222:7682, isLocalConnection=false
18:08:38.453 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49782, local=/128.111.8.222:7682, isLocalConnection=false
18:08:48.499 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49785, local=/128.111.8.222:7682, isLocalConnection=false
18:08:58.508 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49788, local=/128.111.8.222:7682, isLocalConnection=false
18:09:08.519 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49795, local=/128.111.8.222:7682, isLocalConnection=false
18:09:18.541 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49798, local=/128.111.8.222:7682, isLocalConnection=false
18:09:28.617 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49801, local=/128.111.8.222:7682, isLocalConnection=false
18:09:38.630 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49804, local=/128.111.8.222:7682, isLocalConnection=false
18:09:48.630 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49811, local=/128.111.8.222:7682, isLocalConnection=false
18:09:58.638 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49814, local=/128.111.8.222:7682, isLocalConnection=false
18:10:08.651 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49817, local=/128.111.8.222:7682, isLocalConnection=false
18:10:18.654 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49820, local=/128.111.8.222:7682, isLocalConnection=false
18:10:28.669 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49827, local=/128.111.8.222:7682, isLocalConnection=false
18:10:38.671 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49830, local=/128.111.8.222:7682, isLocalConnection=false
18:10:48.683 [nioEventLoopGroup-3-3] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49833, local=/128.111.8.222:7682, isLocalConnection=false
18:10:58.687 [nioEventLoopGroup-3-4] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49836, local=/128.111.8.222:7682, isLocalConnection=false
18:11:08.702 [nioEventLoopGroup-3-5] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49843, local=/128.111.8.222:7682, isLocalConnection=false
18:11:18.704 [nioEventLoopGroup-3-6] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49846, local=/128.111.8.222:7682, isLocalConnection=false
18:11:28.716 [nioEventLoopGroup-3-7] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49849, local=/128.111.8.222:7682, isLocalConnection=false
18:11:38.723 [nioEventLoopGroup-3-8] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49852, local=/128.111.8.222:7682, isLocalConnection=false
18:11:48.775 [nioEventLoopGroup-3-1] INFO  org.labrad.manager.LoginHandler - rem
ote=/128.111.8.73:49859, local=/128.111.8.222:7682, isLocalConnection=false
```

### PR DESCRIPTION
**Pull request by maffoo**
The registry proxy connects to a remote labrad manager to access its registry. This change adds the ability to configure the TLS mode used for this remote connection.

Fixes #37

### CODE REVIEW

**Comment by jwenner** [comment]
1. I don't know enough (or any) scala to judge the code quality.
2. After compiling this branch and running it, I don't notice any difference between this and the 0.5.0 version from bintray. In particular, both on this branch and the 0.5.0 bintray version:
   - With `--tls-required=false` in Target of shortcut: Only get lines such as 
     `16:43:57.622 [nioEventLoopGroup-3-2] INFO  org.labrad.manager.LoginHandler - remote=/127.0.0.1:62100, local=/127.0.0.1:7682, isLocalConnection=true`
     when a new session to the manager is connected (e.g., labrad.connect(), a server/node is opened).
   - Without this flag, get such lines every 10 seconds.

**Comment by maffoo** [comment]
@jwenner, presumably your shortcut also specifies to connect to a remote registry with a command line flag like `--registry=labrad://somehost.edu`, since you're seeing error messages related to the registry proxy. This change allows you to configure that registry connection to not use TLS, by changing that to `--registry=labrad://somehost.edu?tls=off`. Can you give that a try?

**Comment by jwenner** [comment]
FYI, the shortcut target that I've been using has been (note: using Windows 7):

```
C:\scalabrad\scalabrad-0.5.0\scalabrad-0.5.0\bin\labrad.bat
--registry=file:///R:/_LabRADRegistry_/?format=delphi
--tls-required=false
```

**Comment by maffoo** [comment]
Oh, sorry, I misunderstood the error message you were getting. I thought it was this manager trying to connect to a remote registry, but it must be something else that was trying to connect to this manager, failing (because it was not using TLS) and retrying every 10 seconds. Could have been a node server or web interface, for example. So yeah, the change in this PR won't have any effect on what you're doing.

**Comment by jwenner** [comment]
Maybe the data vault server on skynet?

**Comment by maffoo** [comment]
yes, that's also a possibility.

**Comment by jwenner** [comment]
With this PR not fixing the issue (now closed), do you want to close it or leave it in case the external registry becomes a problem?

**Comment by maffoo** [comment]
I'd still like to have this, as it's convenient to be able to configure the remote registry connection.

**Pull request merged**
